debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/board
#    username: uno
#    password: thisisTESTpw!#%&
#    driver-class-name: com.mysql.cj.jdbc.Driver

  url: jdbc:h2:mem:testdb  # in-memory 주소 설정
  username: sa
  driver-class-name: org.h2.Driver


  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: true # in-memory 방식을 사용하는 경우 H2 콘솔을 사용할 것인지의 유무
  sql.init.mode: always
